import TopBar from "@/app/topBar"
import type {Metadata} from "next";
import {Geist, Geist_Mono, Ubuntu} from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({
    variable: "--font-ubuntu", weight: [
        '300',
        '400',
        '500',
        '700'], subsets: ['latin']
});

const geistSans = Geist({
    variable: "--font-geist-sans", subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono", subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode; }>)
{
    return (<html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} ${ubuntu.variable} antialiased`}>
    <div className={'flex flex-col h-screen font-mono transition-all duration-500'}>
        <div className={'w-full h-[10%] border-b-1 border-light-light dark:border-light-dark'}>
            <TopBar/>
        </div>
        <div className={'h-[90%]'}>
            {children}
        </div>
        {/*<div className={'w-full h-[10%] border-t-1 border-light-light dark:border-light-dark'}></div>*/}
    </div>
    </body>
    </html>);
}
